-- 01_crear_esquema_y_tablas.sql
-- Crea el esquema ventas_stock y todas las tablas del modelo físico.

DROP SCHEMA IF EXISTS ventas_stock CASCADE;
CREATE SCHEMA ventas_stock;

CREATE TABLE ventas_stock.disenos (
    id_diseno integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_diseno text NOT NULL,
    CONSTRAINT pk_disenos PRIMARY KEY (id_diseno),
    CONSTRAINT uq_disenos_nombre UNIQUE (nombre_diseno)
);

CREATE TABLE ventas_stock.articulos (
    id_articulo integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_articulo text NOT NULL,
    CONSTRAINT pk_articulos PRIMARY KEY (id_articulo),
    CONSTRAINT uq_articulos_nombre UNIQUE (nombre_articulo)
);

CREATE TABLE ventas_stock.productos_comercializables (
    id_producto_comercializable integer GENERATED BY DEFAULT AS IDENTITY,
    id_diseno integer NOT NULL,
    id_articulo integer NOT NULL,
    precio_referencia_actual numeric(10,0) NOT NULL,
    costo_referencia_actual numeric(10,0) NOT NULL,
    CONSTRAINT pk_productos_comercializables PRIMARY KEY (id_producto_comercializable),
    CONSTRAINT fk_productos_disenos FOREIGN KEY (id_diseno)
        REFERENCES ventas_stock.disenos (id_diseno)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_productos_articulos FOREIGN KEY (id_articulo)
        REFERENCES ventas_stock.articulos (id_articulo)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_productos_diseno_articulo UNIQUE (id_diseno, id_articulo),
    CONSTRAINT chk_productos_precio_no_negativo CHECK (precio_referencia_actual >= 0),
    CONSTRAINT chk_productos_costo_no_negativo CHECK (costo_referencia_actual >= 0)
);

CREATE TABLE ventas_stock.canales_venta (
    id_canal_venta integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_canal_venta text NOT NULL,
    comision_porcentual_canal numeric(5,2),
    CONSTRAINT pk_canales_venta PRIMARY KEY (id_canal_venta),
    CONSTRAINT uq_canales_venta_nombre UNIQUE (nombre_canal_venta),
    CONSTRAINT chk_canales_comision_rango CHECK (
        comision_porcentual_canal IS NULL
        OR (comision_porcentual_canal >= 0 AND comision_porcentual_canal <= 100)
    ),
    CONSTRAINT chk_canales_feria_sin_comision_canal CHECK (
        (nombre_canal_venta = 'Feria' AND comision_porcentual_canal IS NULL)
        OR
        (nombre_canal_venta <> 'Feria' AND comision_porcentual_canal IS NOT NULL)
    )
);

CREATE TABLE ventas_stock.ferias (
    id_feria integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_feria text NOT NULL,
    comision_porcentual_feria numeric(5,2) NOT NULL,
    CONSTRAINT pk_ferias PRIMARY KEY (id_feria),
    CONSTRAINT uq_ferias_nombre UNIQUE (nombre_feria),
    CONSTRAINT chk_ferias_comision_rango CHECK (comision_porcentual_feria >= 0 AND comision_porcentual_feria <= 100)
);

CREATE TABLE ventas_stock.medios_pago (
    id_medio_pago integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_medio_pago text NOT NULL,
    CONSTRAINT pk_medios_pago PRIMARY KEY (id_medio_pago),
    CONSTRAINT uq_medios_pago_nombre UNIQUE (nombre_medio_pago)
);

CREATE TABLE ventas_stock.tipos_movimiento_stock (
    id_tipo_movimiento_stock integer GENERATED BY DEFAULT AS IDENTITY,
    nombre_tipo_movimiento_stock text NOT NULL,
    CONSTRAINT pk_tipos_movimiento_stock PRIMARY KEY (id_tipo_movimiento_stock),
    CONSTRAINT uq_tipos_movimiento_stock_nombre UNIQUE (nombre_tipo_movimiento_stock)
);

CREATE TABLE ventas_stock.ventas (
    id_venta integer GENERATED BY DEFAULT AS IDENTITY,
    fecha_venta date NOT NULL,
    id_canal_venta integer NOT NULL,
    id_feria integer,
    id_medio_pago integer NOT NULL,
    comision_porcentual_aplicada numeric(5,2) NOT NULL,
    CONSTRAINT pk_ventas PRIMARY KEY (id_venta),
    CONSTRAINT fk_ventas_canales FOREIGN KEY (id_canal_venta)
        REFERENCES ventas_stock.canales_venta (id_canal_venta)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_ferias FOREIGN KEY (id_feria)
        REFERENCES ventas_stock.ferias (id_feria)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_ventas_medios_pago FOREIGN KEY (id_medio_pago)
        REFERENCES ventas_stock.medios_pago (id_medio_pago)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT chk_ventas_comision_rango CHECK (comision_porcentual_aplicada >= 0 AND comision_porcentual_aplicada <= 100),
    CONSTRAINT chk_ventas_feria_condicional CHECK (
        (id_canal_venta = 1 AND id_feria IS NOT NULL)
        OR
        (id_canal_venta <> 1 AND id_feria IS NULL)
    )
);

CREATE TABLE ventas_stock.detalle_ventas (
    id_detalle_venta integer GENERATED BY DEFAULT AS IDENTITY,
    id_venta integer NOT NULL,
    id_producto_comercializable integer NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario_historico numeric(10,0) NOT NULL,
    costo_unitario_historico numeric(10,0) NOT NULL,
    CONSTRAINT pk_detalle_ventas PRIMARY KEY (id_detalle_venta),
    CONSTRAINT fk_detalle_ventas_ventas FOREIGN KEY (id_venta)
        REFERENCES ventas_stock.ventas (id_venta)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_detalle_ventas_productos FOREIGN KEY (id_producto_comercializable)
        REFERENCES ventas_stock.productos_comercializables (id_producto_comercializable)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_detalle_venta_producto UNIQUE (id_venta, id_producto_comercializable),
    CONSTRAINT chk_detalle_cantidad_positiva CHECK (cantidad > 0),
    CONSTRAINT chk_detalle_precio_no_negativo CHECK (precio_unitario_historico >= 0),
    CONSTRAINT chk_detalle_costo_no_negativo CHECK (costo_unitario_historico >= 0)
);

CREATE TABLE ventas_stock.movimientos_stock (
    id_movimiento_stock integer GENERATED BY DEFAULT AS IDENTITY,
    id_producto_comercializable integer NOT NULL,
    id_tipo_movimiento_stock integer NOT NULL,
    fecha_movimiento date NOT NULL,
    cantidad integer NOT NULL,
    id_detalle_venta integer,
    CONSTRAINT pk_movimientos_stock PRIMARY KEY (id_movimiento_stock),
    CONSTRAINT fk_movimientos_stock_productos FOREIGN KEY (id_producto_comercializable)
        REFERENCES ventas_stock.productos_comercializables (id_producto_comercializable)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_stock_tipos FOREIGN KEY (id_tipo_movimiento_stock)
        REFERENCES ventas_stock.tipos_movimiento_stock (id_tipo_movimiento_stock)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_stock_detalle FOREIGN KEY (id_detalle_venta)
        REFERENCES ventas_stock.detalle_ventas (id_detalle_venta)
        ON UPDATE RESTRICT ON DELETE RESTRICT,
    CONSTRAINT uq_movimientos_stock_detalle_venta UNIQUE (id_detalle_venta),
    CONSTRAINT chk_movimientos_cantidad_no_cero CHECK (cantidad <> 0),
    CONSTRAINT chk_movimientos_detalle_segun_tipo CHECK (
        (id_tipo_movimiento_stock = 3 AND id_detalle_venta IS NOT NULL)
        OR
        (id_tipo_movimiento_stock <> 3 AND id_detalle_venta IS NULL)
    ),
    CONSTRAINT chk_movimientos_signo_segun_tipo CHECK (
        (id_tipo_movimiento_stock IN (1, 2) AND cantidad > 0)
        OR
        (id_tipo_movimiento_stock IN (3, 4) AND cantidad < 0)
        OR
        (id_tipo_movimiento_stock = 5 AND cantidad <> 0)
    )
);

CREATE INDEX idx_productos_id_diseno ON ventas_stock.productos_comercializables (id_diseno);
CREATE INDEX idx_productos_id_articulo ON ventas_stock.productos_comercializables (id_articulo);
CREATE INDEX idx_ventas_fecha ON ventas_stock.ventas (fecha_venta);
CREATE INDEX idx_ventas_canal ON ventas_stock.ventas (id_canal_venta);
CREATE INDEX idx_ventas_feria ON ventas_stock.ventas (id_feria);
CREATE INDEX idx_detalle_venta ON ventas_stock.detalle_ventas (id_venta);
CREATE INDEX idx_detalle_producto ON ventas_stock.detalle_ventas (id_producto_comercializable);
CREATE INDEX idx_movimientos_producto_fecha ON ventas_stock.movimientos_stock (id_producto_comercializable, fecha_movimiento, id_movimiento_stock);
CREATE INDEX idx_movimientos_tipo ON ventas_stock.movimientos_stock (id_tipo_movimiento_stock);
